export const TNAME_EXPENSE = 'EXPENSE';
export const TNAME_CURRENCY_TYPES = 'CURRENCY_TYPES';
export const TNAME_EXPENSE_CATEGORIES = 'EXPENSE_CATEGORIES';
export const TNAME_PAYMENT_TYPES = 'PAYMENT_TYPES';
