export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const UPDATE_EXPENSE_LIST = 'UPDATE_EXPENSE_LIST';
export const UPDATE_INCOME_LIST = 'UPDATE_INCOME_LIST';
export const UPDATE_CURRENCY_TYPES = 'UPDATE_CURRENCY_TYPES';
export const UPDATE_SUMMARY = 'UPDATE_SUMMARY';
