export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const UPDATE_EXPENSE_LIST = 'UPDATE_EXPENSE_LIST';
export const UPDATE_INCOME_LIST = 'UPDATE_INCOME_LIST';
export const UPDATE_CURRENCY_TYPES = 'UPDATE_CURRENCY_TYPES';
export const UPDATE_SUMMARY = 'UPDATE_SUMMARY';
